# Generated by Django 4.2.7 on 2023-12-04 13:18

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("full_name", models.CharField(default="", max_length=255)),
                ("phone_number", models.CharField(default="", max_length=15)),
                ("address", models.CharField(default="", max_length=255)),
                ("age", models.IntegerField(default=0)),
                ("pin_code", models.CharField(default="", max_length=10)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("CategoryID", models.AutoField(primary_key=True, serialize=False)),
                ("CategoryName", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                ("locationId", models.AutoField(primary_key=True, serialize=False)),
                ("address1", models.CharField(max_length=255)),
                ("address2", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=255)),
                ("postcode", models.CharField(max_length=10)),
                ("country", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                ("ServiceID", models.AutoField(primary_key=True, serialize=False)),
                ("ServiceName", models.CharField(max_length=255)),
                ("Description", models.TextField()),
                ("Price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "CategoryID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.category"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("EmployeeID", models.AutoField(primary_key=True, serialize=False)),
                ("Employee_name", models.CharField(default="", max_length=255)),
                ("Date_of_birth", models.DateField()),
                ("Phone_number", models.CharField(default="", max_length=15)),
                ("Address", models.CharField(default="", max_length=255)),
                ("Age", models.IntegerField(default=0)),
                ("Pin_code", models.CharField(default="", max_length=10)),
                ("Rating", models.DecimalField(decimal_places=1, max_digits=3)),
                ("Charge", models.IntegerField()),
                ("Location", models.CharField(default="", max_length=255)),
                (
                    "CategoryID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.category"
                    ),
                ),
                (
                    "ServiceID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.service"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("AppointmentID", models.AutoField(primary_key=True, serialize=False)),
                ("ServiceDate", models.DateField()),
                ("AppointmentDate", models.DateField()),
                ("AppointmentTime", models.TimeField()),
                (
                    "EmployeeID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.employee"
                    ),
                ),
                (
                    "ServiceID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.service"
                    ),
                ),
                (
                    "UserID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "locationId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.location"
                    ),
                ),
            ],
        ),
    ]
