# Generated by Django 4.2.7 on 2023-11-26 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("CategoryID", models.AutoField(primary_key=True, serialize=False)),
                ("CategoryName", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                ("ServiceID", models.AutoField(primary_key=True, serialize=False)),
                ("ServiceName", models.CharField(max_length=255)),
                ("Description", models.TextField()),
                ("Price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "CategoryID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.category"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("EmployeeID", models.AutoField(primary_key=True, serialize=False)),
                ("Employee_name", models.CharField(default="", max_length=255)),
                ("Date_of_birth", models.DateField()),
                ("Phone_number", models.CharField(default="", max_length=15)),
                ("Address", models.CharField(default="", max_length=255)),
                ("Age", models.IntegerField(default=0)),
                ("Pin_code", models.CharField(default="", max_length=10)),
                (
                    "CategoryID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.category"
                    ),
                ),
                (
                    "ServiceID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.service"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("AppointmentID", models.AutoField(primary_key=True, serialize=False)),
                ("AppointmentDate", models.DateField()),
                ("AppointmentTime", models.TimeField()),
                (
                    "ServiceID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.service"
                    ),
                ),
                (
                    "UserID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
