# Generated by Django 4.2.7 on 2023-12-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="Caption",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="category",
            name="Imageurl",
            field=models.CharField(default="", max_length=255),
        ),
    ]
