# Generated by Django 4.2.7 on 2023-12-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_category_caption_category_imageurl"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="ShortDescription",
            field=models.CharField(default="", max_length=255),
        ),
    ]
